package rtcqueue

import "github.com/redis/go-redis/v9"

// claimScript atomically claims a session: checks the lock, inspects the
// queue, sets the lock, pops the highest-priority work, and updates its
// status to processing. Also stores the active work ID in session:active
// so CancelSession can find it later. Returns [workID] or nil when there
// is nothing to claim.
//
// KEYS[1] = session lock
// KEYS[2] = session queue (zset)
// KEYS[3] = session active work pointer ("session:active:<sessionID>")
// ARGV[1] = worker_id
// ARGV[2] = lock ttl seconds
// ARGV[3] = now (unix seconds)
var claimScript = redis.NewScript(`
if redis.call("EXISTS", KEYS[1]) == 1 then
    return nil
end
if redis.call("ZCARD", KEYS[2]) == 0 then
    return nil
end
if redis.call("SET", KEYS[1], ARGV[1], "NX", "EX", tonumber(ARGV[2])) == false then
    return nil
end
local popped = redis.call("ZPOPMIN", KEYS[2], 1)
if #popped == 0 then
    return nil
end
local work_id = popped[1]
redis.call("HSET", "work:" .. work_id,
    "status", "processing",
    "worker_id", ARGV[1],
    "claimed_at", ARGV[3],
    "updated_at", ARGV[3])
redis.call("SET", KEYS[3], work_id)
return {work_id}
`)

// claimWithCredentialScript claims a work item with credential-based lock ownership.
// If the lock doesn't exist, creates it with the provided credential (first claim).
// If the lock exists and credential matches, continues claiming (subsequent claim).
// If the lock exists but credential doesn't match, returns nil (access denied).
//
// KEYS[1] = session lock (hash: worker_id, credential)
// KEYS[2] = session queue (zset)
// KEYS[3] = session active work pointer
// ARGV[1] = worker_id
// ARGV[2] = credential (generated by Go, UUID format)
// ARGV[3] = lock ttl seconds
// ARGV[4] = now (unix seconds)
// Returns: {work_id, credential} or nil
var claimWithCredentialScript = redis.NewScript(`
local lock_exists = redis.call("EXISTS", KEYS[1]) == 1

if lock_exists then
    -- Lock exists, check credential
    local stored_cred = redis.call("HGET", KEYS[1], "credential")
    if stored_cred ~= ARGV[2] then
        -- Credential mismatch, access denied
        return nil
    end
    -- Credential matches, continue claiming
    if redis.call("ZCARD", KEYS[2]) == 0 then
        return nil
    end
    -- Renew lock TTL
    redis.call("EXPIRE", KEYS[1], tonumber(ARGV[3]))
else
    -- Lock doesn't exist, first claim
    if redis.call("ZCARD", KEYS[2]) == 0 then
        return nil
    end
    -- Create lock with worker_id and credential
    redis.call("HSET", KEYS[1], "worker_id", ARGV[1], "credential", ARGV[2])
    redis.call("EXPIRE", KEYS[1], tonumber(ARGV[3]))
end

-- Pop work from queue
local popped = redis.call("ZPOPMIN", KEYS[2], 1)
if #popped == 0 then
    return nil
end
local work_id = popped[1]
redis.call("HSET", "work:" .. work_id,
    "status", "processing",
    "worker_id", ARGV[1],
    "claimed_at", ARGV[4],
    "updated_at", ARGV[4])
redis.call("SET", KEYS[3], work_id)

-- Get credential (either existing or newly created)
local cred = redis.call("HGET", KEYS[1], "credential")
return {work_id, cred}
`)

// publishScript atomically persists a Work item, enqueues it in the
// session's priority queue, and notifies workers.
//
// KEYS[1] = work hash key ("work:<work_id>")
// KEYS[2] = session queue (zset)
// ARGV[1]  = work_id
// ARGV[2]  = session_id
// ARGV[3]  = data
// ARGV[4]  = priority (signed integer string)
// ARGV[5]  = created_at (unix seconds)
// ARGV[6]  = updated_at (unix seconds)
// ARGV[7]  = channel name for notification
// ARGV[8]  = session_id notification payload
var publishScript = redis.NewScript(`
local work_id = KEYS[1]:sub(6)
redis.call("HSET", KEYS[1],
    "id",         ARGV[1],
    "session_id", ARGV[2],
    "data",       ARGV[3],
    "priority",   ARGV[4],
    "status",     "pending",
    "created_at", ARGV[5],
    "updated_at", ARGV[6],
    "worker_id",  "",
    "claimed_at", "0")
redis.call("ZADD", KEYS[2], 0 - tonumber(ARGV[4]), work_id)
redis.call("PUBLISH", ARGV[7], ARGV[8])
return 1
`)

// completeScript marks a Work item completed and releases the session
// lock in one atomic step. Also clears the session:active pointer.
// If the session's queue still has pending work items, publishes a
// session:new notification so workers can claim the next item.
//
// KEYS[1] = work hash key
// ARGV[1] = now (unix seconds)
// ARGV[2] = session:new channel name
var completeScript = redis.NewScript(`
local sid = redis.call("HGET", KEYS[1], "session_id")
if not sid then
    return 0
end
redis.call("HSET", KEYS[1], "status", "completed", "updated_at", ARGV[1])
redis.call("DEL", "session:lock:" .. sid)
redis.call("DEL", "session:active:" .. sid)
-- Check if there are pending work items in the queue
local queue_key = "queue:session:" .. sid
if redis.call("ZCARD", queue_key) > 0 then
    -- Notify workers to claim the next item
    redis.call("PUBLISH", ARGV[2], sid)
end
return 1
`)

// completeWorkScript marks a Work item completed WITHOUT releasing the session lock.
// Only clears the session:active pointer. Used for "hold lock" mode where the worker
// continues processing subsequent work items.
//
// KEYS[1] = work hash key
// KEYS[2] = session active pointer
// ARGV[1] = now (unix seconds)
var completeWorkScript = redis.NewScript(`
local sid = redis.call("HGET", KEYS[1], "session_id")
if not sid then
    return 0
end
redis.call("HSET", KEYS[1], "status", "completed", "updated_at", ARGV[1])
redis.call("DEL", KEYS[2])
return 1
`)

// cancelScript cancels a Work item. If it was pending, it is removed
// from the session queue. A cancel notification is always published so
// any worker holding the session lock can abort. The lock is released.
// Also clears the session:active pointer.
//
// KEYS[1] = work hash key
// ARGV[1] = now (unix seconds)
// ARGV[2] = cancel message payload (JSON)
var cancelScript = redis.NewScript(`
local sid = redis.call("HGET", KEYS[1], "session_id")
if not sid then
    return 0
end
local status = redis.call("HGET", KEYS[1], "status")
if status == "completed" or status == "cancelled" then
    return -1
end
if status == "pending" then
    redis.call("ZREM", "queue:session:" .. sid, KEYS[1]:sub(6))
end
redis.call("HSET", KEYS[1], "status", "cancelled", "updated_at", ARGV[1])
-- notify subscribers BEFORE releasing the lock: otherwise a competing
-- worker in a tight claimScript retry loop can acquire the lock between
-- DEL and PUBLISH and start processing while the cancel notification is
-- still in flight. Subscribers must see the cancel first.
redis.call("PUBLISH", "session:cancel:" .. sid, ARGV[2])
redis.call("DEL", "session:lock:" .. sid)
redis.call("DEL", "session:active:" .. sid)
return 1
`)

// cancelSessionScript removes all pending work items from a session's queue
// atomically, marks them as cancelled, and returns their work IDs.
//
// KEYS[1] = session queue (zset) "queue:session:<sessionID>"
// ARGV[1] = now (unix seconds)
// Returns: array of removed work IDs (may be empty).
var cancelSessionScript = redis.NewScript(`
local ids = redis.call("ZRANGE", KEYS[1], 0, -1)
if #ids > 0 then
    redis.call("DEL", KEYS[1])
    for i, wid in ipairs(ids) do
        redis.call("HSET", "work:" .. wid, "status", "cancelled", "updated_at", ARGV[1])
    end
end
return ids
`)

// cancelSessionActiveScript cancels the work item currently being processed
// for a session (if any). It reads the session:active pointer, marks the work
// as cancelled in the work hash (so workers can detect cancellation even if
// the Pub/Sub message is lost), publishes a cancel notification, and releases
// both the session lock and the active pointer. Publish happens BEFORE
// releasing the lock to prevent a race where a competing worker acquires the
// lock between DEL and PUBLISH.
//
// KEYS[1] = session lock ("session:lock:<sessionID>")
// KEYS[2] = session active pointer ("session:active:<sessionID>")
// KEYS[3] = session cancel channel ("session:cancel:<sessionID>")
// ARGV[1] = reason
// ARGV[2] = now (unix seconds)
// Returns: workID that was cancelled, or nil if no active work.
var cancelSessionActiveScript = redis.NewScript(`
local work_id = redis.call("GET", KEYS[2])
if not work_id then
    return nil
end
redis.call("DEL", KEYS[2])
-- Persist the cancelled status to the work hash. This is critical for
-- reliability: if the PUBLISH below is lost (e.g. the worker hasn't
-- subscribed yet), the worker can still detect the cancellation by
-- checking the work status after LoadWork. Without this, a lost Pub/Sub
-- message means the worker never learns the work was cancelled.
redis.call("HSET", "work:" .. work_id, "status", "cancelled", "updated_at", ARGV[2])
local msg = cjson.encode({
    work_id = work_id,
    reason = ARGV[1],
    timestamp = tonumber(ARGV[2])
})
-- publish BEFORE releasing the lock (see cancelScript for rationale)
redis.call("PUBLISH", KEYS[3], msg)
redis.call("DEL", KEYS[1])
return work_id
`)

// renewLockScript atomically refreshes the session lock TTL only if it
// is still owned by the calling worker. The read+compare+expire dance
// MUST be atomic — otherwise the lock can expire between GET and
// EXPIRE, be re-acquired by a different worker via claimScript, and
// the stale EXPIRE would silently extend the new owner's hold.
//
// KEYS[1] = session lock
// ARGV[1] = worker_id (expected owner)
// ARGV[2] = lock ttl seconds
// Returns 1 on success, 0 if the lock is missing or owned by someone
// else.
var renewLockScript = redis.NewScript(`
if redis.call("GET", KEYS[1]) ~= ARGV[1] then
    return 0
end
return redis.call("EXPIRE", KEYS[1], tonumber(ARGV[2]))
`)

// renewLockWithCredentialScript atomically refreshes the session lock TTL
// only if it is still owned by the calling worker with the correct credential.
// This is the hash-based lock version used in "hold lock" mode.
//
// KEYS[1] = session lock (hash: worker_id, credential)
// ARGV[1] = worker_id (expected owner)
// ARGV[2] = credential (expected credential)
// ARGV[3] = lock ttl seconds
// Returns 1 on success, 0 if the lock is missing or owned by someone else.
var renewLockWithCredentialScript = redis.NewScript(`
local stored_worker = redis.call("HGET", KEYS[1], "worker_id")
local stored_cred = redis.call("HGET", KEYS[1], "credential")
if stored_worker ~= ARGV[1] or stored_cred ~= ARGV[2] then
    return 0
end
return redis.call("EXPIRE", KEYS[1], tonumber(ARGV[3]))
`)

// completeAndClaimNextScript atomically completes the current work item and
// claims the next work item from the session queue if available. This enables
// "hold lock" mode where a worker can process multiple work items without
// releasing and re-acquiring the session lock.
//
// KEYS[1] = current work hash key ("work:<work_id>")
// KEYS[2] = session queue (zset) "queue:session:<sessionID>"
// KEYS[3] = session active work pointer ("session:active:<sessionID>")
// KEYS[4] = session lock hash ("session:lock:<sessionID>")
// ARGV[1] = now (unix seconds)
// ARGV[2] = worker_id
// ARGV[3] = lock ttl seconds
// Returns: {next_work_id, credential} if next work exists, nil otherwise.
var completeAndClaimNextScript = redis.NewScript(`
-- Complete current work
local sid = redis.call("HGET", KEYS[1], "session_id")
if not sid then
    return nil
end
redis.call("HSET", KEYS[1], "status", "completed", "updated_at", ARGV[1])
redis.call("DEL", KEYS[3])

-- Verify lock is still held
local stored_worker = redis.call("HGET", KEYS[4], "worker_id")
if stored_worker ~= ARGV[2] then
    return nil
end

-- Check if there's next work in queue
if redis.call("ZCARD", KEYS[2]) == 0 then
    return nil
end

-- Pop next work from queue
local popped = redis.call("ZPOPMIN", KEYS[2], 1)
if #popped == 0 then
    return nil
end
local next_work_id = popped[1]
redis.call("HSET", "work:" .. next_work_id,
    "status", "processing",
    "worker_id", ARGV[2],
    "claimed_at", ARGV[1],
    "updated_at", ARGV[1])
redis.call("SET", KEYS[3], next_work_id)

-- Renew lock TTL
redis.call("EXPIRE", KEYS[4], tonumber(ARGV[3]))

-- Get credential
local cred = redis.call("HGET", KEYS[4], "credential")
return {next_work_id, cred}
`)

// completeWorkAndClaimNextScript atomically completes the current work item and
// attempts to claim the next pending work item for the same session. Unlike
// completeAndClaimNextScript, this script verifies credential ownership via the
// hash-based session lock, ensuring only the legitimate worker can complete and
// claim in "hold lock" mode.
//
// KEYS[1] = work hash key (current work, "work:<work_id>")
// KEYS[2] = session lock (hash: worker_id, credential, "session:lock:<sessionID>")
// KEYS[3] = session queue (zset, "queue:session:<sessionID>")
// KEYS[4] = session active work pointer ("session:active:<sessionID>")
// ARGV[1] = current work ID
// ARGV[2] = worker ID
// ARGV[3] = credential
// ARGV[4] = current time (unix seconds)
// ARGV[5] = lock TTL seconds
// Returns: {next_work_id, credential} or empty
var completeWorkAndClaimNextScript = redis.NewScript(`
local work_key = KEYS[1]
local lock_key = KEYS[2]
local queue_key = KEYS[3]
local active_key = KEYS[4]
local current_work_id = ARGV[1]
local worker_id = ARGV[2]
local credential = ARGV[3]
local now = tonumber(ARGV[4])
local ttl = tonumber(ARGV[5])

-- Verify lock is held by this worker with correct credential
local stored_worker = redis.call("HGET", lock_key, "worker_id")
local stored_cred = redis.call("HGET", lock_key, "credential")
if stored_worker ~= worker_id or stored_cred ~= credential then
    return {}
end

-- Mark current work as completed
redis.call("HSET", work_key, "status", "completed", "updated_at", now)

-- Check if there's next work in queue
local next_work = redis.call("ZPOPMIN", queue_key, 1)
if #next_work == 0 then
    -- No more work, clear active pointer
    redis.call("DEL", active_key)
    return {}
end

local next_work_id = next_work[1]

-- Update the next work item status to processing
redis.call("HSET", "work:" .. next_work_id,
    "status", "processing",
    "worker_id", worker_id,
    "claimed_at", now,
    "updated_at", now)

-- Update active pointer
redis.call("SET", active_key, next_work_id)

-- Renew lock TTL
redis.call("EXPIRE", lock_key, ttl)

return {next_work_id, credential}
`)

// requeueWorkScript atomically moves a work item from "processing" back to
// "pending" and re-adds it to the session's priority queue. This prevents
// "ghost work" — items claimed from Redis but never processed because the
// target TurnLoop had already stopped (e.g., Push failed after ClaimWithCredential
// succeeded).
//
// KEYS[1] = work hash key ("work:<work_id>")
// KEYS[2] = session queue (zset) "queue:session:<sessionID>"
// ARGV[1] = now (unix seconds)
// Returns 1 on success, 0 if work not found or not in "processing" state.
var requeueWorkScript = redis.NewScript(`
local status = redis.call("HGET", KEYS[1], "status")
if not status then
    return 0
end
if status ~= "processing" then
    return 0
end
local sid = redis.call("HGET", KEYS[1], "session_id")
if not sid then
    return 0
end
local priority = tonumber(redis.call("HGET", KEYS[1], "priority"))
if not priority then
    priority = 0
end
local work_id = KEYS[1]:sub(6)
redis.call("HSET", KEYS[1],
    "status", "pending",
    "worker_id", "",
    "claimed_at", "0",
    "updated_at", ARGV[1])
redis.call("ZADD", KEYS[2], 0 - priority, work_id)
return 1
`)
