// Package protocol provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package protocol

import (
	"time"
)

// Defines values for ContentType.
const (
	ContentTypeMarkdown       ContentType = "markdown"
	ContentTypeSummary        ContentType = "summary"
	ContentTypeText           ContentType = "text"
	ContentTypeThinking       ContentType = "thinking"
	ContentTypeToolCallInput  ContentType = "toolcall_input"
	ContentTypeToolCallOutput ContentType = "toolcall_output"
)

// Valid indicates whether the value is a known member of the ContentType enum.
func (e ContentType) Valid() bool {
	switch e {
	case ContentTypeMarkdown:
		return true
	case ContentTypeSummary:
		return true
	case ContentTypeText:
		return true
	case ContentTypeThinking:
		return true
	case ContentTypeToolCallInput:
		return true
	case ContentTypeToolCallOutput:
		return true
	default:
		return false
	}
}

// Defines values for MessageRole.
const (
	MessageRoleAssistant MessageRole = "assistant"
	MessageRoleSystem    MessageRole = "system"
	MessageRoleTool      MessageRole = "tool"
	MessageRoleUser      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case MessageRoleAssistant:
		return true
	case MessageRoleSystem:
		return true
	case MessageRoleTool:
		return true
	case MessageRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for MessageStreamingStatus.
const (
	MessageStreamingCompleted MessageStreamingStatus = "completed"
	MessageStreamingFailed    MessageStreamingStatus = "failed"
	MessageStreamingPending   MessageStreamingStatus = "pending"
	MessageStreamingStreaming MessageStreamingStatus = "streaming"
)

// Valid indicates whether the value is a known member of the MessageStreamingStatus enum.
func (e MessageStreamingStatus) Valid() bool {
	switch e {
	case MessageStreamingCompleted:
		return true
	case MessageStreamingFailed:
		return true
	case MessageStreamingPending:
		return true
	case MessageStreamingStreaming:
		return true
	default:
		return false
	}
}

// Defines values for RpcMethod.
const (
	MethodMessageGet      RpcMethod = "v1.message.get"
	MethodMessageList     RpcMethod = "v1.message.list"
	MethodMessageSend     RpcMethod = "v1.message.send"
	MethodRtcGet          RpcMethod = "v1.rtc.get"
	MethodRtcList         RpcMethod = "v1.rtc.list"
	MethodRtcSubmitResult RpcMethod = "v1.rtc.submit_result"
	MethodRtcUpdateStatus RpcMethod = "v1.rtc.update_status"
	MethodSessionClose    RpcMethod = "v1.session.close"
	MethodSessionFork     RpcMethod = "v1.session.fork"
	MethodSessionGet      RpcMethod = "v1.session.get"
	MethodSessionList     RpcMethod = "v1.session.list"
	MethodSessionUpdate   RpcMethod = "v1.session.update"
	MethodTurnGet         RpcMethod = "v1.turn.get"
	MethodTurnList        RpcMethod = "v1.turn.list"
	MethodTurnStop        RpcMethod = "v1.turn.stop"
)

// Valid indicates whether the value is a known member of the RpcMethod enum.
func (e RpcMethod) Valid() bool {
	switch e {
	case MethodMessageGet:
		return true
	case MethodMessageList:
		return true
	case MethodMessageSend:
		return true
	case MethodRtcGet:
		return true
	case MethodRtcList:
		return true
	case MethodRtcSubmitResult:
		return true
	case MethodRtcUpdateStatus:
		return true
	case MethodSessionClose:
		return true
	case MethodSessionFork:
		return true
	case MethodSessionGet:
		return true
	case MethodSessionList:
		return true
	case MethodSessionUpdate:
		return true
	case MethodTurnGet:
		return true
	case MethodTurnList:
		return true
	case MethodTurnStop:
		return true
	default:
		return false
	}
}

// Defines values for RtcStatus.
const (
	RtcStatusCompleted RtcStatus = "completed"
	RtcStatusExecuting RtcStatus = "executing"
	RtcStatusFailed    RtcStatus = "failed"
	RtcStatusPending   RtcStatus = "pending"
	RtcStatusRejected  RtcStatus = "rejected"
	RtcStatusSent      RtcStatus = "sent"
	RtcStatusTimeout   RtcStatus = "timeout"
)

// Valid indicates whether the value is a known member of the RtcStatus enum.
func (e RtcStatus) Valid() bool {
	switch e {
	case RtcStatusCompleted:
		return true
	case RtcStatusExecuting:
		return true
	case RtcStatusFailed:
		return true
	case RtcStatusPending:
		return true
	case RtcStatusRejected:
		return true
	case RtcStatusSent:
		return true
	case RtcStatusTimeout:
		return true
	default:
		return false
	}
}

// Defines values for SessionStatus.
const (
	SessionStatusActive SessionStatus = "active"
	SessionStatusClosed SessionStatus = "closed"
	SessionStatusIdle   SessionStatus = "idle"
)

// Valid indicates whether the value is a known member of the SessionStatus enum.
func (e SessionStatus) Valid() bool {
	switch e {
	case SessionStatusActive:
		return true
	case SessionStatusClosed:
		return true
	case SessionStatusIdle:
		return true
	default:
		return false
	}
}

// Defines values for TurnStatus.
const (
	TurnStatusCancelled   TurnStatus = "cancelled"
	TurnStatusCompleted   TurnStatus = "completed"
	TurnStatusFailed      TurnStatus = "failed"
	TurnStatusInterrupted TurnStatus = "interrupted"
	TurnStatusMerged      TurnStatus = "merged"
	TurnStatusPending     TurnStatus = "pending"
	TurnStatusRunning     TurnStatus = "running"
)

// Valid indicates whether the value is a known member of the TurnStatus enum.
func (e TurnStatus) Valid() bool {
	switch e {
	case TurnStatusCancelled:
		return true
	case TurnStatusCompleted:
		return true
	case TurnStatusFailed:
		return true
	case TurnStatusInterrupted:
		return true
	case TurnStatusMerged:
		return true
	case TurnStatusPending:
		return true
	case TurnStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for UpdateAction.
const (
	ActionCreated UpdateAction = "created"
	ActionDeleted UpdateAction = "deleted"
	ActionUpdated UpdateAction = "updated"
)

// Valid indicates whether the value is a known member of the UpdateAction enum.
func (e UpdateAction) Valid() bool {
	switch e {
	case ActionCreated:
		return true
	case ActionDeleted:
		return true
	case ActionUpdated:
		return true
	default:
		return false
	}
}

// Defines values for UpdateEntity.
const (
	EntityMessage UpdateEntity = "message"
	EntityRtc     UpdateEntity = "rtc"
	EntitySession UpdateEntity = "session"
	EntityTurn    UpdateEntity = "turn"
)

// Valid indicates whether the value is a known member of the UpdateEntity enum.
func (e UpdateEntity) Valid() bool {
	switch e {
	case EntityMessage:
		return true
	case EntityRtc:
		return true
	case EntitySession:
		return true
	case EntityTurn:
		return true
	default:
		return false
	}
}

// Defines values for UpdateType.
const (
	UpdateTypeGap UpdateType = "gap"
)

// Valid indicates whether the value is a known member of the UpdateType enum.
func (e UpdateType) Valid() bool {
	switch e {
	case UpdateTypeGap:
		return true
	default:
		return false
	}
}

// CloseSessionRequest defines model for CloseSessionRequest.
type CloseSessionRequest struct {
	// ClientId 客户端生成的幂等 ID
	ClientId *string `json:"client_id,omitempty"`

	// SessionId protocol 内 UUID 类型，JSON 线上为字符串
	SessionId UUID `json:"session_id"`
}

// CloseSessionResponse 关闭会话响应
type CloseSessionResponse struct {
	Result  CloseSessionResult `json:"result"`
	Updates *[]Update          `json:"updates,omitempty"`
}

// CloseSessionResult defines model for CloseSessionResult.
type CloseSessionResult struct {
	Success bool `json:"success"`
}

// ContentData 消息内容数据，Type 标识 Data 的具体结构，前端根据 Type 决定如何渲染
type ContentData struct {
	// Data 具体内容（结构由 type 决定）
	Data interface{} `json:"data"`
	Type ContentType `json:"type"`
}

// ContentType defines model for ContentType.
type ContentType string

// ForkSessionRequest 分叉对话
type ForkSessionRequest struct {
	// ContentData 消息内容数据，Type 标识 Data 的具体结构，前端根据 Type 决定如何渲染
	ContentData ContentData `json:"content_data"`

	// Limit Fork 多少条消息？默认200；最多1000条；
	Limit *int `json:"limit,omitempty"`

	// NewClientMessageId 客户端生成的幂等 ID
	NewClientMessageId string `json:"new_client_message_id"`

	// NewClientSessionId protocol 内 UUID 类型，JSON 线上为字符串
	NewClientSessionId UUID `json:"new_client_session_id"`

	// OldServerMessageId protocol 内 UUID 类型，JSON 线上为字符串
	OldServerMessageId UUID `json:"old_server_message_id"`

	// OldServerSessionId protocol 内 UUID 类型，JSON 线上为字符串
	OldServerSessionId UUID `json:"old_server_session_id"`
}

// ForkSessionResponse Fork对话响应
type ForkSessionResponse struct {
	Result  ForkSessionResult `json:"result"`
	Updates *[]Update         `json:"updates,omitempty"`
}

// ForkSessionResult defines model for ForkSessionResult.
type ForkSessionResult struct {
	MessageIds []UUID `json:"message_ids"`

	// SessionId protocol 内 UUID 类型，JSON 线上为字符串
	SessionId UUID `json:"session_id"`

	// TurnId protocol 内 UUID 类型，JSON 线上为字符串
	TurnId UUID `json:"turn_id"`
}

// GetSessionRequest defines model for GetSessionRequest.
type GetSessionRequest struct {
	// SessionId protocol 内 UUID 类型，JSON 线上为字符串
	SessionId UUID `json:"session_id"`
}

// GetSessionResponse defines model for GetSessionResponse.
type GetSessionResponse struct {
	Item Session `json:"item"`
}

// ListSessionsRequest 获取会话列表请求
type ListSessionsRequest struct {
	// Cursor 分页游标（上一页最后一条的 ID）
	Cursor *string `json:"cursor,omitempty"`

	// Limit 每页数量，默认 20
	Limit *int `json:"limit,omitempty"`
}

// ListSessionsResponse defines model for ListSessionsResponse.
type ListSessionsResponse struct {
	Items []Session `json:"items"`

	// NextCursor 下一页游标，为空表示没有更多数据
	NextCursor *string `json:"next_cursor,omitempty"`
}

// Message defines model for Message.
type Message struct {
	// ClientId 客户端生成的幂等 ID
	ClientId *string `json:"client_id,omitempty"`

	// Content 消息内容
	Content   *string   `json:"content,omitempty"`
	CreatedAt time.Time `json:"created_at"`

	// CreatorKind 创建者类型（user / system）
	CreatorKind string `json:"creator_kind"`

	// CreatorRefId 创建者引用 ID
	CreatorRefId string `json:"creator_ref_id"`

	// DeletedAt 软删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`

	// GlobalOffset Session 内全局顺序
	GlobalOffset uint32 `json:"global_offset"`

	// Id protocol 内 UUID 类型，JSON 线上为字符串
	Id UUID `json:"id"`

	// ParentMessageId protocol 内 UUID 类型，JSON 线上为字符串
	ParentMessageId *UUID       `json:"parent_message_id,omitempty"`
	Role            MessageRole `json:"role"`

	// SessionId protocol 内 UUID 类型，JSON 线上为字符串
	SessionId       UUID                   `json:"session_id"`
	StreamingStatus MessageStreamingStatus `json:"streaming_status"`

	// TurnId protocol 内 UUID 类型，JSON 线上为字符串
	TurnId *UUID `json:"turn_id,omitempty"`

	// TurnOffset Turn 内顺序
	TurnOffset *uint32   `json:"turn_offset,omitempty"`
	UpdatedAt  time.Time `json:"updated_at"`
}

// MessageGetRequest defines model for MessageGetRequest.
type MessageGetRequest struct {
	// MessageId protocol 内 UUID 类型，JSON 线上为字符串
	MessageId UUID `json:"message_id"`
}

// MessageGetResponse defines model for MessageGetResponse.
type MessageGetResponse struct {
	Item Message `json:"item"`
}

// MessageListRequest 获取消息列表请求
type MessageListRequest struct {
	// Cursor 分页游标（上一页最后一条的 global_offset）
	Cursor *uint32 `json:"cursor,omitempty"`

	// Limit 每页数量，默认 50
	Limit *int `json:"limit,omitempty"`

	// SessionId protocol 内 UUID 类型，JSON 线上为字符串
	SessionId UUID `json:"session_id"`
}

// MessageListResponse defines model for MessageListResponse.
type MessageListResponse struct {
	Items []Message `json:"items"`

	// NextCursor 下一页游标
	NextCursor *uint32 `json:"next_cursor,omitempty"`
}

// MessageRole defines model for MessageRole.
type MessageRole string

// MessageStreamingStatus defines model for MessageStreamingStatus.
type MessageStreamingStatus string

// OAuth2AuthorizeResponse defines model for OAuth2AuthorizeResponse.
type OAuth2AuthorizeResponse struct {
	RedirectUrl string `json:"redirect_url"`
	State       string `json:"state"`
}

// OAuth2Error OAuth2 通用错误响应
type OAuth2Error struct {
	// Error invalid_request / invalid_client / invalid_grant / server_error
	Error            string  `json:"error"`
	ErrorDescription *string `json:"error_description,omitempty"`
}

// OAuth2TokenExchangeRequest defines model for OAuth2TokenExchangeRequest.
type OAuth2TokenExchangeRequest struct {
	// Code OAuth2 授权码
	Code string `json:"code"`

	// DeviceId 前端生成的设备 UUID
	DeviceId string `json:"device_id"`

	// DeviceName 设备名称（如 "Chrome on Mac"）
	DeviceName *string `json:"device_name,omitempty"`

	// RedirectUri 重定向 URI
	RedirectUri string `json:"redirect_uri"`

	// State CSRF 防护 state
	State string `json:"state"`

	// UserAgent User-Agent 字符串
	UserAgent *string `json:"user_agent,omitempty"`
}

// OAuth2TokenExchangeResponse defines model for OAuth2TokenExchangeResponse.
type OAuth2TokenExchangeResponse struct {
	// AccessToken JWT access token
	AccessToken string `json:"access_token"`

	// ExpiresIn access token 过期时间（秒）
	ExpiresIn int64 `json:"expires_in"`

	// RefreshToken refresh token
	RefreshToken string `json:"refresh_token"`

	// UserId 用户 ID
	UserId string `json:"user_id"`
}

// OAuth2TokenRefreshRequest defines model for OAuth2TokenRefreshRequest.
type OAuth2TokenRefreshRequest struct {
	// RefreshToken refresh token
	RefreshToken string `json:"refresh_token"`
}

// OAuth2TokenRefreshResponse defines model for OAuth2TokenRefreshResponse.
type OAuth2TokenRefreshResponse struct {
	// AccessToken 新的 JWT access token
	AccessToken string `json:"access_token"`

	// ExpiresIn access token 过期时间（秒）
	ExpiresIn int64 `json:"expires_in"`
}

// RpcMethod RPC 方法名，前后端统一从 protocol 导入，禁止硬编码字符串
type RpcMethod string

// Rtc 远程 Tool 调用模型
type Rtc struct {
	// ClientId 客户端生成的幂等 ID
	ClientId *string `json:"client_id,omitempty"`

	// CompletedAt 完成时间
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`

	// DeletedAt 软删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`

	// ErrorMessage 错误信息（失败时）
	ErrorMessage *string `json:"error_message,omitempty"`

	// Id protocol 内 UUID 类型，JSON 线上为字符串
	Id UUID `json:"id"`

	// MessageId protocol 内 UUID 类型，JSON 线上为字符串
	MessageId *UUID `json:"message_id,omitempty"`

	// Offset Turn 内的顺序
	Offset uint32 `json:"offset"`

	// OutputMessageId protocol 内 UUID 类型，JSON 线上为字符串
	OutputMessageId *UUID `json:"output_message_id,omitempty"`

	// Parameters Tool 参数（JSON Schema）
	Parameters interface{} `json:"parameters,omitempty"`

	// Result 执行结果
	Result interface{} `json:"result,omitempty"`

	// SessionId protocol 内 UUID 类型，JSON 线上为字符串
	SessionId UUID      `json:"session_id"`
	Status    RtcStatus `json:"status"`

	// ToolName Tool 名称
	ToolName string `json:"tool_name"`

	// TurnId protocol 内 UUID 类型，JSON 线上为字符串
	TurnId    UUID      `json:"turn_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

// RtcGetRequest defines model for RtcGetRequest.
type RtcGetRequest struct {
	// RtcId protocol 内 UUID 类型，JSON 线上为字符串
	RtcId UUID `json:"rtc_id"`
}

// RtcGetResponse defines model for RtcGetResponse.
type RtcGetResponse struct {
	// Item 远程 Tool 调用模型
	Item Rtc `json:"item"`
}

// RtcListRequest 获取 RTC 列表请求
type RtcListRequest struct {
	// Cursor 分页游标（上一页最后一条的 ID）
	Cursor *string `json:"cursor,omitempty"`

	// Limit 每页数量，默认 50
	Limit *int `json:"limit,omitempty"`

	// SessionId protocol 内 UUID 类型，JSON 线上为字符串
	SessionId UUID `json:"session_id"`
}

// RtcListResponse defines model for RtcListResponse.
type RtcListResponse struct {
	Items []Rtc `json:"items"`

	// NextCursor 下一页游标
	NextCursor *string `json:"next_cursor,omitempty"`
}

// RtcStatus defines model for RtcStatus.
type RtcStatus string

// SendMessageRequest 发送消息请求，自动创建 session（如不存在）和 turn
type SendMessageRequest struct {
	// ClientId 客户端生成的幂等 ID
	ClientId string `json:"client_id"`

	// ClientSessionId 必填
	ClientSessionId string `json:"client_session_id"`

	// ContentData 消息内容数据，Type 标识 Data 的具体结构，前端根据 Type 决定如何渲染
	ContentData ContentData `json:"content_data"`

	// ServerSessionId protocol 内 UUID 类型，JSON 线上为字符串
	ServerSessionId *UUID `json:"server_session_id,omitempty"`
}

// SendMessageResponse 发送消息响应
type SendMessageResponse struct {
	Result  SendMessageResult `json:"result"`
	Updates *[]Update         `json:"updates,omitempty"`
}

// SendMessageResult defines model for SendMessageResult.
type SendMessageResult struct {
	// MessageId protocol 内 UUID 类型，JSON 线上为字符串
	MessageId UUID `json:"message_id"`

	// SessionId protocol 内 UUID 类型，JSON 线上为字符串
	SessionId UUID `json:"session_id"`

	// TurnId protocol 内 UUID 类型，JSON 线上为字符串
	TurnId UUID `json:"turn_id"`
}

// Session defines model for Session.
type Session struct {
	// ClientId 客户端生成的幂等 ID
	ClientId *string `json:"client_id,omitempty"`

	// ClosedAt 关闭时间
	ClosedAt  *time.Time `json:"closed_at,omitempty"`
	CreatedAt time.Time  `json:"created_at"`

	// DeletedAt 软删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`

	// Id protocol 内 UUID 类型，JSON 线上为字符串
	Id UUID `json:"id"`

	// OwnerKind 所有者类型（user / system）
	OwnerKind string `json:"owner_kind"`

	// OwnerRefId 所有者引用 ID（user → user UUID，system → "system"）
	OwnerRefId string        `json:"owner_ref_id"`
	Status     SessionStatus `json:"status"`

	// Title 会话标题
	Title     *string   `json:"title,omitempty"`
	UpdatedAt time.Time `json:"updated_at"`
}

// SessionStatus defines model for SessionStatus.
type SessionStatus string

// StopTurnRequest defines model for StopTurnRequest.
type StopTurnRequest struct {
	// ClientId 客户端生成的幂等 ID
	ClientId *string `json:"client_id,omitempty"`

	// SessionId protocol 内 UUID 类型，JSON 线上为字符串
	SessionId UUID `json:"session_id"`
}

// StopTurnResponse 停止 Turn 响应
type StopTurnResponse struct {
	Result  StopTurnResult `json:"result"`
	Updates *[]Update      `json:"updates,omitempty"`
}

// StopTurnResult defines model for StopTurnResult.
type StopTurnResult struct {
	Success bool `json:"success"`
}

// SubmitRtcResultRequest 提交 RTC 执行结果请求
type SubmitRtcResultRequest struct {
	// ClientId 客户端生成的幂等 ID
	ClientId *string `json:"client_id,omitempty"`

	// Error 错误信息（失败时）
	Error *string `json:"error,omitempty"`

	// Result 执行结果（成功时）
	Result interface{} `json:"result,omitempty"`

	// RtcId protocol 内 UUID 类型，JSON 线上为字符串
	RtcId UUID `json:"rtc_id"`

	// Success 是否执行成功
	Success bool `json:"success"`
}

// SubmitRtcResultResponse 提交 RTC 执行结果响应
type SubmitRtcResultResponse struct {
	Result  SubmitRtcResultResult `json:"result"`
	Updates *[]Update             `json:"updates,omitempty"`
}

// SubmitRtcResultResult defines model for SubmitRtcResultResult.
type SubmitRtcResultResult struct {
	Success bool `json:"success"`
}

// ToolCall defines model for ToolCall.
type ToolCall struct {
	// Id protocol 内 UUID 类型，JSON 线上为字符串
	Id       UUID    `json:"id"`
	Input    string  `json:"input"`
	Output   *string `json:"output,omitempty"`
	Status   *string `json:"status,omitempty"`
	ToolName string  `json:"tool_name"`
}

// Turn defines model for Turn.
type Turn struct {
	// ClientId 客户端生成的幂等 ID
	ClientId *string `json:"client_id,omitempty"`

	// CompletedAt 完成时间
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`

	// DeletedAt 软删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`

	// ErrorMessage 错误信息（失败时）
	ErrorMessage *string `json:"error_message,omitempty"`

	// Id protocol 内 UUID 类型，JSON 线上为字符串
	Id UUID `json:"id"`

	// SessionId protocol 内 UUID 类型，JSON 线上为字符串
	SessionId UUID `json:"session_id"`

	// StartedAt 开始执行时间
	StartedAt *time.Time `json:"started_at,omitempty"`
	Status    TurnStatus `json:"status"`
}

// TurnGetRequest defines model for TurnGetRequest.
type TurnGetRequest struct {
	// TurnId protocol 内 UUID 类型，JSON 线上为字符串
	TurnId UUID `json:"turn_id"`
}

// TurnGetResponse defines model for TurnGetResponse.
type TurnGetResponse struct {
	Item Turn `json:"item"`
}

// TurnListRequest 获取 Turn 列表请求
type TurnListRequest struct {
	// Cursor 分页游标（上一页最后一条的 ID）
	Cursor *string `json:"cursor,omitempty"`

	// Limit 每页数量，默认 50
	Limit *int `json:"limit,omitempty"`

	// SessionId protocol 内 UUID 类型，JSON 线上为字符串
	SessionId UUID `json:"session_id"`
}

// TurnListResponse defines model for TurnListResponse.
type TurnListResponse struct {
	Items []Turn `json:"items"`

	// NextCursor 下一页游标
	NextCursor *string `json:"next_cursor,omitempty"`
}

// TurnStatus defines model for TurnStatus.
type TurnStatus string

// UUID protocol 内 UUID 类型，JSON 线上为字符串
type UUID = string

// Update 实体变化事件，随操作类 RPC 响应下发，前端收到后更新本地状态保持实时同步
type Update struct {
	// DataList 实体数据（可选，与 items 一一对应）
	DataList *[]interface{} `json:"data_list,omitempty"`

	// Id protocol 内 UUID 类型，JSON 线上为字符串
	Id UUID `json:"id"`

	// Items 变化条目列表
	Items []UpdateItem `json:"items"`

	// Offset 用户维度单调递增 offset
	Offset uint32 `json:"offset"`
}

// UpdateAction defines model for UpdateAction.
type UpdateAction string

// UpdateDataGap gap 占位数据，客户端收到后只推进 offset，不做业务处理
type UpdateDataGap = map[string]interface{}

// UpdateEntity defines model for UpdateEntity.
type UpdateEntity string

// UpdateItem 单条实体变化记录
type UpdateItem struct {
	Action UpdateAction `json:"action"`
	Entity UpdateEntity `json:"entity"`

	// EntityId protocol 内 UUID 类型，JSON 线上为字符串
	EntityId UUID `json:"entity_id"`
}

// UpdateRtcStatusRequest defines model for UpdateRtcStatusRequest.
type UpdateRtcStatusRequest struct {
	// ClientId 客户端生成的幂等 ID
	ClientId *string `json:"client_id,omitempty"`

	// RtcId protocol 内 UUID 类型，JSON 线上为字符串
	RtcId  UUID      `json:"rtc_id"`
	Status RtcStatus `json:"status"`
}

// UpdateRtcStatusResponse 更新 RTC 状态响应
type UpdateRtcStatusResponse struct {
	Result  UpdateRtcStatusResult `json:"result"`
	Updates *[]Update             `json:"updates,omitempty"`
}

// UpdateRtcStatusResult defines model for UpdateRtcStatusResult.
type UpdateRtcStatusResult struct {
	Success bool `json:"success"`
}

// UpdateSessionRequest 更新会话请求（目前仅支持标题）
type UpdateSessionRequest struct {
	// SessionId protocol 内 UUID 类型，JSON 线上为字符串
	SessionId UUID `json:"session_id"`

	// Title 新标题（不传表示不修改）
	Title *string `json:"title,omitempty"`
}

// UpdateSessionResponse 更新会话响应
type UpdateSessionResponse struct {
	Result  UpdateSessionResult `json:"result"`
	Updates *[]Update           `json:"updates,omitempty"`
}

// UpdateSessionResult defines model for UpdateSessionResult.
type UpdateSessionResult struct {
	// SessionId protocol 内 UUID 类型，JSON 线上为字符串
	SessionId UUID `json:"session_id"`
}

// UpdateType defines model for UpdateType.
type UpdateType string

// GetOAuth2RedirectUrlParams defines parameters for GetOAuth2RedirectUrl.
type GetOAuth2RedirectUrlParams struct {
	// Provider OAuth2 Provider 名称（如 "github"）
	Provider string `form:"provider" json:"provider"`

	// RedirectUri 客户端回调地址（Provider 授权完成后重定向到此地址）
	RedirectUri string `form:"redirect_uri" json:"redirect_uri"`
}

// Oauth2TokenRefreshJSONRequestBody defines body for Oauth2TokenRefresh for application/json ContentType.
type Oauth2TokenRefreshJSONRequestBody = OAuth2TokenRefreshRequest

// Oauth2TokenExchangeJSONRequestBody defines body for Oauth2TokenExchange for application/json ContentType.
type Oauth2TokenExchangeJSONRequestBody = OAuth2TokenExchangeRequest
