// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"fmt"
	"github.com/centrifugal/centrifuge"
	"github.com/cloudwego/eino/components/model"
	"github.com/google/wire"
	"github.com/redis/go-redis/v9"
	"github.com/rtc-agent/server/internal/agent"
	"github.com/rtc-agent/server/internal/auth"
	"github.com/rtc-agent/server/internal/channel"
	"github.com/rtc-agent/server/internal/config"
	"github.com/rtc-agent/server/internal/httphandler"
	"github.com/rtc-agent/server/internal/oauth2provider"
	"github.com/rtc-agent/server/internal/repo"
	"github.com/rtc-agent/server/internal/rpchandler"
	"github.com/rtc-agent/server/internal/server"
	"github.com/rtc-agent/server/internal/statestore"
	"github.com/rtc-agent/server/internal/svc"
	"github.com/rtc-agent/server/internal/updates"
	"github.com/rtc-agent/server/internal/usecase"
	"github.com/rtc-agent/server/pkg/centrifuge-plus"
	"github.com/rtc-agent/server/pkg/logger"
	"github.com/rtc-agent/server/pkg/rtc-queue"
	"github.com/rtc-agent/server/pkg/turn-agent"
	"gorm.io/gorm"
	"time"
)

// Injectors from wire.go:

// InitializeServiceContext builds the ServiceContext using Wire.
func InitializeServiceContext(cfg *config.Config, db *gorm.DB, rdb *redis.Client) (*svc.ServiceContext, error) {
	universalClient := provideRedisUniversal(rdb)
	sessionRepo := repo.NewSessionRepo(db)
	messageRepo := repo.NewMessageRepo(db)
	turnRepo := repo.NewTurnRepo(db)
	rtcRepo := repo.NewRtcRepo(db)
	oAuth2UserRepo := repo.NewOAuth2UserRepo(db)
	deviceRepo := repo.NewDeviceRepo(db)
	refreshTokenRepo := repo.NewRefreshTokenRepo(db)
	updatePublisher := provideUpdatePublisher(db, universalClient, sessionRepo, messageRepo, turnRepo, rtcRepo)
	node, err := provideCentrifugeNode()
	if err != nil {
		return nil, err
	}
	jwtSigner, err := provideJWTSigner(cfg)
	if err != nil {
		return nil, err
	}
	dualBroker, err := provideDualBroker(cfg, node, updatePublisher, jwtSigner)
	if err != nil {
		return nil, err
	}
	serviceContext := svc.NewServiceContextWithDeps(cfg, db, universalClient, sessionRepo, messageRepo, turnRepo, rtcRepo, oAuth2UserRepo, deviceRepo, refreshTokenRepo, updatePublisher, node, dualBroker, jwtSigner)
	return serviceContext, nil
}

// InitializeServer builds the entire Server using Wire.
func InitializeServer(cfg *config.Config, db *gorm.DB, rdb *redis.Client) (*server.Server, error) {
	universalClient := provideRedisUniversal(rdb)
	sessionRepo := repo.NewSessionRepo(db)
	messageRepo := repo.NewMessageRepo(db)
	turnRepo := repo.NewTurnRepo(db)
	rtcRepo := repo.NewRtcRepo(db)
	oAuth2UserRepo := repo.NewOAuth2UserRepo(db)
	deviceRepo := repo.NewDeviceRepo(db)
	refreshTokenRepo := repo.NewRefreshTokenRepo(db)
	updatePublisher := provideUpdatePublisher(db, universalClient, sessionRepo, messageRepo, turnRepo, rtcRepo)
	node, err := provideCentrifugeNode()
	if err != nil {
		return nil, err
	}
	jwtSigner, err := provideJWTSigner(cfg)
	if err != nil {
		return nil, err
	}
	dualBroker, err := provideDualBroker(cfg, node, updatePublisher, jwtSigner)
	if err != nil {
		return nil, err
	}
	serviceContext := svc.NewServiceContextWithDeps(cfg, db, universalClient, sessionRepo, messageRepo, turnRepo, rtcRepo, oAuth2UserRepo, deviceRepo, refreshTokenRepo, updatePublisher, node, dualBroker, jwtSigner)
	cmdChatModelResult, err := provideChatModel(cfg)
	if err != nil {
		return nil, err
	}
	dependencies := provideUsecaseDependencies(serviceContext, cmdChatModelResult, cfg)
	queue := provideQueue(rdb)
	handler := provideRPCHandler(dependencies, sessionRepo, queue, cfg)
	httphandlerHandler := provideHTTPHandler(serviceContext)
	redisStore := provideStateStore(universalClient)
	client := provideOAuth2ProviderClient(cfg)
	oAuth2Handler := provideOAuth2Handler(serviceContext, jwtSigner, redisStore, client, cfg)
	interruptHandler := provideInterruptHandler(universalClient, cfg)
	agent, err := provideAgent(dependencies, universalClient, cfg)
	if err != nil {
		return nil, err
	}
	worker := provideQueueWorker(queue, agent, cfg)
	streamStore := provideStreamStore(universalClient, cfg)
	serverServer := provideServer(cfg, serviceContext, handler, httphandlerHandler, oAuth2Handler, interruptHandler, worker, streamStore)
	return serverServer, nil
}

// wire.go:

// RepositorySet provides all repository implementations.
var RepositorySet = wire.NewSet(repo.NewSessionRepo, repo.NewMessageRepo, repo.NewTurnRepo, repo.NewRtcRepo, repo.NewOAuth2UserRepo, repo.NewDeviceRepo, repo.NewRefreshTokenRepo)

// ServiceSet provides core services (UpdatePublisher, JWTSigner, Centrifuge).
var ServiceSet = wire.NewSet(
	provideRedisUniversal,
	provideUpdatePublisher,
	provideJWTSigner,
	provideCentrifugeNode,
	provideDualBroker,
)

// UsecaseSet provides usecase layer dependencies.
var UsecaseSet = wire.NewSet(
	provideChatModel,
	provideUsecaseDependencies,
)

// QueueSet provides rtc-queue components.
var QueueSet = wire.NewSet(
	provideQueue,
	provideStreamStore,
	provideAgent,
	provideQueueWorker,
)

// HandlerSet provides all HTTP and RPC handlers.
var HandlerSet = wire.NewSet(
	provideStateStore,
	provideOAuth2ProviderClient,
	provideRPCHandler,
	provideHTTPHandler,
	provideOAuth2Handler,
	provideInterruptHandler,
)

// ServerSet provides the main Server.
var ServerSet = wire.NewSet(
	provideServer,
)

func provideRedisUniversal(rdb *redis.Client) redis.UniversalClient {
	return rdb
}

func provideUpdatePublisher(
	db *gorm.DB,
	redisClient redis.UniversalClient,
	sessionRepo repo.SessionRepo,
	messageRepo repo.MessageRepo,
	turnRepo repo.TurnRepo,
	rtcRepo repo.RtcRepo,
) *updates.UpdatePublisher {
	return updates.NewUpdatePublisher(db, redisClient, sessionRepo, messageRepo, turnRepo, rtcRepo)
}

func provideJWTSigner(cfg *config.Config) (*auth.JWTSigner, error) {
	return auth.NewJWTSigner(cfg.Auth.JWTSecret, time.Duration(cfg.Auth.AccessTokenTTLSeconds)*time.Second)
}

func provideCentrifugeNode() (*centrifuge.Node, error) {
	return centrifuge.New(centrifuge.Config{
		LogLevel: centrifuge.LogLevelInfo,
	})
}

func provideDualBroker(
	cfg *config.Config,
	node *centrifuge.Node,
	updatePublisher *updates.UpdatePublisher,
	jwtSigner *auth.JWTSigner,
) (*centrifugeplus.DualBroker, error) {

	redisShard, err := centrifuge.NewRedisShard(node, centrifuge.RedisShardConfig{
		Address: cfg.Redis.Addr,
	})
	if err != nil {
		return nil, fmt.Errorf("create redis shard: %w", err)
	}

	broker, err := centrifugeplus.NewDualBroker(node, centrifugeplus.DualBrokerConfig{
		Live: centrifuge.RedisBrokerConfig{
			Prefix: channel.LivePrefix,
			Shards: []*centrifuge.RedisShard{redisShard},
		},
		Topic: centrifugeplus.TopicBrokerConfig{
			Prefix:        channel.TopicPrefix,
			RedisAddr:     cfg.Redis.Addr,
			RedisPassword: cfg.Redis.Password,
			RedisDB:       cfg.Redis.DB,
			HistoryStore:  updatePublisher,
		},
	})
	if err != nil {
		return nil, fmt.Errorf("create broker: %w", err)
	}

	if err := svc.SetupCentrifuge(node, broker, jwtSigner, cfg.Server.RPCTimeout); err != nil {
		return nil, fmt.Errorf("setup centrifuge: %w", err)
	}

	return broker, nil
}

// chatModelResult wraps the optional ChatModel to handle Wire's error semantics.
type chatModelResult struct {
	model model.ChatModel
}

func provideChatModel(cfg *config.Config) (*chatModelResult, error) {
	if cfg.LLM.Provider == "" || cfg.LLM.Model == "" {
		logger.Warn("LLM not configured (provider/model missing), agent features will be disabled")
		return &chatModelResult{model: nil}, nil
	}

	m, err := server.NewChatModel(cfg)
	if err != nil {
		logger.Error("Failed to create chat model: %v (agent features will be disabled)", err)
		return &chatModelResult{model: nil}, nil
	}
	logger.Info("LLM initialized: provider=%s model=%s", cfg.LLM.Provider, cfg.LLM.Model)
	return &chatModelResult{model: m}, nil
}

func provideUsecaseDependencies(
	svcCtx *svc.ServiceContext, chatModelResult2 *chatModelResult,
	cfg *config.Config,
) *usecase.Dependencies {
	return &usecase.Dependencies{
		DB:              svcCtx.DB,
		Redis:           svcCtx.Redis,
		SessionRepo:     svcCtx.SessionRepo,
		MessageRepo:     svcCtx.MessageRepo,
		TurnRepo:        svcCtx.TurnRepo,
		RtcRepo:         svcCtx.RtcRepo,
		UpdatePublisher: svcCtx.UpdatePublisher,
		ChatModel:       chatModelResult2.model,
		SystemPrompt:    cfg.Worker.SystemPrompt,
		WorkerConfig:    cfg.Worker,
	}
}

func provideQueue(rdb *redis.Client) *rtcqueue.Queue {
	return rtcqueue.New(rdb)
}

func provideStreamStore(redisClient redis.UniversalClient, cfg *config.Config) *agent.StreamStore {
	return agent.NewStreamStore(redisClient, cfg.Worker.StreamChunkTTL)
}

func provideAgent(
	deps *usecase.Dependencies,
	redisClient redis.UniversalClient,
	cfg *config.Config,
) (*turnagent.Agent, error) {
	return agent.New(agent.Config{
		Deps:               deps,
		Redis:              redisClient,
		ContextTokensLimit: cfg.Worker.ContextTokensLimit,
		EnableLLMLogging:   logger.DebugMode,
		CheckpointTTL:      cfg.Worker.CheckpointTTL,
		StreamChunkTTL:     cfg.Worker.StreamChunkTTL,
		Logger:             agent.NewLogger(),
	})
}

func provideQueueWorker(
	queue *rtcqueue.Queue, agent2 *turnagent.Agent,
	cfg *config.Config,
) *rtcqueue.Worker {
	workerID := cfg.Worker.WorkerID
	if workerID == "" {
		workerID = "worker-" + cfg.Server.Host
	}

	return rtcqueue.NewWorker(queue, rtcqueue.WorkerConfig{
		WorkerID:    workerID,
		Concurrency: cfg.Worker.BackgroundConcurrency,
		OnWork:      agent2.Process,
		OnError: func(err error) {
			logger.Error("[rtcqueue.Worker] error: %v", err)
		},
	})
}

func provideStateStore(redisClient redis.UniversalClient) *statestore.RedisStore {
	return statestore.NewRedisStore(redisClient)
}

func provideOAuth2ProviderClient(cfg *config.Config) *oauth2provider.Client {
	providers := server.BuildProviderClients(cfg)
	return oauth2provider.NewClient(providers, cfg.Providers.HTTPTimeout)
}

func provideRPCHandler(
	deps *usecase.Dependencies,
	sessionRepo repo.SessionRepo,
	queue *rtcqueue.Queue,
	cfg *config.Config,
) *rpchandler.Handler {
	handler := rpchandler.NewHandler(&rpchandler.Dependencies{
		Deps:        deps,
		SessionRepo: sessionRepo,
		Queue:       queue,
		API:         cfg.API,
	})
	svc.RegisterRPCHandler(handler)
	return handler
}

func provideHTTPHandler(svcCtx *svc.ServiceContext) *httphandler.Handler {
	return httphandler.NewHandler(svcCtx)
}

func provideOAuth2Handler(
	svcCtx *svc.ServiceContext,
	jwtSigner *auth.JWTSigner,
	stateStore *statestore.RedisStore,
	providerClient *oauth2provider.Client,
	cfg *config.Config,
) *httphandler.OAuth2Handler {
	return httphandler.NewOAuth2Handler(svcCtx, jwtSigner, stateStore, providerClient, cfg.Auth)
}

func provideInterruptHandler(
	redisClient redis.UniversalClient,
	cfg *config.Config,
) *httphandler.InterruptHandler {
	return httphandler.NewInterruptHandler(redisClient, cfg.Worker)
}

func provideServer(
	cfg *config.Config,
	svcCtx *svc.ServiceContext,
	rpcHandler *rpchandler.Handler,
	httpHandler *httphandler.Handler,
	oauth2Handler *httphandler.OAuth2Handler,
	interruptHandler *httphandler.InterruptHandler,
	queueWorker *rtcqueue.Worker,
	streamStore *agent.StreamStore,
) *server.Server {

	svcCtx.UpdatePublisher.SetStreamStore(streamStore)

	return server.NewWithDeps(
		cfg,
		svcCtx,
		rpcHandler,
		httpHandler,
		oauth2Handler,
		interruptHandler,
		queueWorker,
	)
}
