package turnagent

import "github.com/cloudwego/eino/schema"

// Role constants for Message.Role. Mirror the values used by eino's
// schema.RoleType, but the upper application uses these string constants
// and never imports eino for this purpose.
const (
	RoleUser      = "user"
	RoleAssistant = "assistant"
	RoleSystem    = "system"
	RoleTool      = "tool"
)

// Message is the pkg-level message type, independent of eino's schema.Message.
// The upper application builds and consumes Messages without importing eino.
//
// Conversion to/from schema.Message happens inside the pkg (see the unexported
// helpers at the bottom of this file). Application code does not call those
// helpers — it works only with Message.
type Message struct {
	// Role is one of RoleUser, RoleAssistant, RoleSystem, RoleTool.
	Role string

	// Content is the main text content (user input, assistant output, tool
	// result).
	Content string

	// ReasoningContent is the model's thinking / reasoning trace, populated on
	// assistant messages when the model supports it.
	ReasoningContent string

	// ToolName identifies the tool that produced this message. Populated when
	// Role == RoleTool.
	ToolName string

	// ToolCallID links a tool result message back to the assistant's tool call.
	// Populated when Role == RoleTool.
	ToolCallID string

	// Name is an optional display name for the message sender.
	Name string

	// FinishReason is set on the final assistant message of a response (e.g.,
	// "stop", "tool_calls", "length"). Empty on non-final messages and on
	// non-assistant roles.
	FinishReason string

	// ToolCalls describes the tool calls the assistant wants to make. Populated
	// only on assistant messages; empty on other roles.
	ToolCalls []ToolCall

	// Extra carries application-specific metadata. The pkg preserves this map
	// across conversions without interpreting it.
	Extra map[string]any

	// TurnID is the turn that created this message. Optional — user messages
	// created by the API layer don't have a turnID yet (the turn is created
	// later by turn-agent when the worker processes the work item). Assistant
	// messages generated by the agent have a turnID.
	//
	// TurnID is used for:
	//   - Linking messages to their generating turn for observability
	//   - Filtering messages by turn (e.g., "show me messages from turn X")
	//   - TurnOffset calculations (see below)
	//
	// Note: TurnID is NOT mapped to/from eino's schema.Message during
	// conversion — it is metadata that lives at the dbmodel layer and is
	// populated by the turn-agent when persisting messages, not by eino's
	// chat-model pipeline.
	TurnID string

	// TurnOffset is the position of this message within its turn's output.
	// 0 = first message in the turn, 1 = second, etc. Used for ordering
	// when multiple messages are generated in the same turn (e.g., streaming
	// chunks that become separate message rows, or an assistant message
	// followed by tool-call messages all produced by one turn).
	//
	// Like TurnID, this is not mapped through eino conversion — it is a
	// persistence-layer concern.
	TurnOffset int
}

// ToolCall describes one tool invocation requested by the assistant.
type ToolCall struct {
	// ID is the tool call's unique identifier, used to correlate with the
	// matching tool result message (Message.ToolCallID).
	ID string

	// Name is the tool's registered name.
	Name string

	// Arguments is the JSON-encoded arguments to pass to the tool.
	Arguments string
}

// =============================================================================
// Internal conversion helpers (not exposed to the upper application)
// =============================================================================

// toEinoMessage converts a pkg Message to eino's schema.Message. Returns nil
// for nil input.
//
// NOTE: TurnID and TurnOffset are intentionally NOT mapped to eino's
// schema.Message — they are persistence-layer metadata (used to link a
// message back to the turn that created it) that eino's chat-model pipeline
// does not need to know about. If round-tripping through eino is required
// and TurnID/TurnOffset must be preserved, store them in Extra before
// conversion and restore them afterward.
func toEinoMessage(m *Message) *schema.Message {
	if m == nil {
		return nil
	}
	em := &schema.Message{
		Role:               schema.RoleType(m.Role),
		Content:            m.Content,
		ReasoningContent:   m.ReasoningContent,
		ToolName:           m.ToolName,
		ToolCallID:         m.ToolCallID,
		Name:               m.Name,
		Extra:              m.Extra,
	}
	for _, tc := range m.ToolCalls {
		em.ToolCalls = append(em.ToolCalls, schema.ToolCall{
			ID: tc.ID,
			Function: schema.FunctionCall{
				Name:      tc.Name,
				Arguments: tc.Arguments,
			},
		})
	}
	return em
}

// toEinoMessages converts a slice of pkg Messages to eino's message slice.
// Preserves order; nil input returns nil output.
func toEinoMessages(msgs []*Message) []*schema.Message {
	if msgs == nil {
		return nil
	}
	out := make([]*schema.Message, len(msgs))
	for i, m := range msgs {
		out[i] = toEinoMessage(m)
	}
	return out
}

// fromEinoMessage converts an eino schema.Message to a pkg Message. Returns nil
// for nil input.
func fromEinoMessage(m *schema.Message) *Message {
	if m == nil {
		return nil
	}
	msg := &Message{
		Role:             string(m.Role),
		Content:          m.Content,
		ReasoningContent: m.ReasoningContent,
		ToolName:         m.ToolName,
		ToolCallID:       m.ToolCallID,
		Name:             m.Name,
		Extra:            m.Extra,
	}
	if m.ResponseMeta != nil {
		msg.FinishReason = m.ResponseMeta.FinishReason
	}
	for _, tc := range m.ToolCalls {
		msg.ToolCalls = append(msg.ToolCalls, ToolCall{
			ID:        tc.ID,
			Name:      tc.Function.Name,
			Arguments: tc.Function.Arguments,
		})
	}
	return msg
}
